import { Router } from "express";
import authRoutes from "./auth.routes";
import masterProductRoutes from "./masterProduct.routes";
import vendorListingRoutes from "./vendorListing.routes";
import shopRoutes from "./shop.routes";
import masterCategoryRoutes from "./masterCategory.routes";
import categoryRoutes from "./category.routes";
import brandRoutes from "./brand.routes";
import customerProductRoutes from "./customerProduct.routes";
import cartRoutes from "./cart.routes";
import wishlistRoutes from "./wishlist.routes";
import addressRoutes from "./address.routes";
import checkoutRoutes from "./checkout.routes";
import orderRoutes from "./order.routes";
import couponRoutes from "./coupon.routes";
import webhookRoutes from "./webhook.routes";
import invoiceRoutes from "./invoice.routes";
import invoiceEmailRoutes from "./invoiceEmail.routes";
import returnRefundRoutes from "./returnRefund.routes";
import settlementRoutes from "./settlement.routes";
import taxClassRoutes from "./taxClass.routes";
import inventoryAdminRoutes from "./inventoryAdmin.routes";
import dashboardRoutes from "./dashboard.routes";
import payoutRoutes from "./payout.routes";
import warehouseRoutes from "./warehouse.routes";
import procurementRoutes from "./procurement.routes";
import lowStockRoutes from "./lowStock.routes";
import gstReportRoutes from "./gstReport.routes";
import refundReconciliationRoutes from "./refundReconciliation.routes";
import vendorFundAccountRoutes from "./vendorFundAccount.routes";
import stockTransferRoutes from "./stockTransfer.routes";
import stockAdjustmentRoutes from "./stockAdjustment.routes";
import purchaseReturnRoutes from "./purchaseReturn.routes";
import notificationRoutes from "./notification.routes";
import jobRoutes from "./job.routes";
import exportRoutes from "./export.routes";
import vendorDashboardRoutes from "./vendorDashboard.routes";
import allocationRoutes from "./allocation.routes";
import creditNoteRoutes from "./creditNote.routes";
import queueRoutes from "./queue.routes";
import fulfillmentRoutes from "./fulfillment.routes";
import expiryRoutes from "./expiry.routes";
import creditNotePdfRoutes from "./creditNotePdf.routes";
import emailQueueProcessorRoutes from "./emailQueueProcessor.routes";
import reconciliationRoutes from "./reconciliation.routes";

const router = Router();

router.use("/auth", authRoutes);
router.use("/shops", shopRoutes);
router.use("/master-categories", masterCategoryRoutes);
router.use("/categories", categoryRoutes);
router.use("/brands", brandRoutes);
router.use("/tax-classes", taxClassRoutes);
router.use("/master-products", masterProductRoutes);
router.use("/vendor-listings", vendorListingRoutes);

router.use("/products", customerProductRoutes);
router.use("/cart", cartRoutes);
router.use("/wishlist", wishlistRoutes);
router.use("/addresses", addressRoutes);
router.use("/checkout", checkoutRoutes);
router.use("/orders", orderRoutes);
router.use("/coupons", couponRoutes);
router.use("/webhooks", webhookRoutes);
router.use("/invoices", invoiceRoutes);
router.use("/invoice-email", invoiceEmailRoutes);
router.use("/after-sales", returnRefundRoutes);
router.use("/settlements", settlementRoutes);
router.use("/inventory-admin", inventoryAdminRoutes);
router.use("/dashboard", dashboardRoutes);
router.use("/payouts", payoutRoutes);

router.use("/warehouses", warehouseRoutes);
router.use("/procurement", procurementRoutes);
router.use("/low-stock", lowStockRoutes);
router.use("/gst-reports", gstReportRoutes);
router.use("/refund-reconciliation", refundReconciliationRoutes);

router.use("/vendor-fund-accounts", vendorFundAccountRoutes);
router.use("/stock-transfers", stockTransferRoutes);
router.use("/stock-adjustments", stockAdjustmentRoutes);
router.use("/purchase-returns", purchaseReturnRoutes);
router.use("/notifications", notificationRoutes);
router.use("/jobs", jobRoutes);
router.use("/exports", exportRoutes);

router.use("/vendor-dashboard", vendorDashboardRoutes);
router.use("/allocations", allocationRoutes);
router.use("/credit-notes", creditNoteRoutes);
router.use("/queue", queueRoutes);

router.use("/fulfillment", fulfillmentRoutes);
router.use("/expiry", expiryRoutes);
router.use("/credit-note-pdf", creditNotePdfRoutes);
router.use("/email-queue", emailQueueProcessorRoutes);
router.use("/reconciliation", reconciliationRoutes);

export default router;