export const PERMISSIONS = {
  ADMIN_ALL: "ADMIN_ALL",

  SHOP_READ: "SHOP_READ",
  SHOP_WRITE: "SHOP_WRITE",

  PRODUCT_READ: "PRODUCT_READ",
  PRODUCT_WRITE: "PRODUCT_WRITE",

  INVENTORY_READ: "INVENTORY_READ",
  INVENTORY_WRITE: "INVENTORY_WRITE",

  ORDER_READ: "ORDER_READ",
  ORDER_WRITE: "ORDER_WRITE",

  PAYOUT_READ: "PAYOUT_READ",
  PAYOUT_WRITE: "PAYOUT_WRITE",

  REPORT_READ: "REPORT_READ",
  SYSTEM_READ: "SYSTEM_READ",
} as const;

export type PermissionKey = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];